document.addEventListener("DOMContentLoaded", () => {
    const sidebar = document.getElementById("sidebar");
    const backdrop = document.getElementById("sidebarBackdrop");
    const menuButton = document.getElementById("menuButton");
    const closeButton = document.getElementById("closeSidebar");
    const newChatButton = document.getElementById("newChatButton");
    const chatHistory = document.getElementById("chatHistory");
    const chatArea = document.getElementById("chatArea");
    const welcome = document.getElementById("welcome");
    const attachButton = document.getElementById("attachButton");
    const screenshotButton = document.getElementById("screenshotButton");
    const fileInput = document.getElementById("fileInput");
    const messageInput = document.getElementById("messageInput");
    const voiceButton = document.getElementById("voiceButton");
    const sendButton = document.getElementById("sendButton");
    const attachmentPreview = document.getElementById("attachmentPreview");

    const API_BASE = "";
    const STORAGE_KEY = "zono_ai_chats_v3";

    let chats = [];
    let activeChatId = null;
    let pendingFiles = [];
    let fileMode = "attach";
    let recognition = null;
    let isSending = false;

    function uid() {
        return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
    }

    function escapeHtml(value) {
        return String(value ?? "")
            .replaceAll("&", "&amp;")
            .replaceAll("<", "&lt;")
            .replaceAll(">", "&gt;")
            .replaceAll('"', "&quot;")
            .replaceAll("'", "&#039;");
    }

    function saveChats() {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(chats));
    }

    function loadChats() {
        try {
            const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
            chats = Array.isArray(saved) ? saved : [];
        } catch {
            chats = [];
        }

        if (!chats.length) {
            createChat(false);
        } else {
            activeChatId = chats[0].id;
            renderHistory();
            renderActiveChat();
        }
    }

    function createChat(save = true) {
        const chat = {
            id: uid(),
            title: "New Chat",
            messages: []
        };

        chats.unshift(chat);
        activeChatId = chat.id;

        if (save) saveChats();
        renderHistory();
        renderActiveChat();
        closeSidebarMobile();
        messageInput.focus();
    }

    function getActiveChat() {
        return chats.find(chat => chat.id === activeChatId);
    }

    function renderHistory() {
        chatHistory.innerHTML = "";

        chats.forEach(chat => {
            const button = document.createElement("button");
            button.className = "history-item" + (chat.id === activeChatId ? " active" : "");
            button.type = "button";
            button.textContent = chat.title || "New Chat";
            button.title = chat.title || "New Chat";

            button.addEventListener("click", () => {
                activeChatId = chat.id;
                renderHistory();
                renderActiveChat();
                closeSidebarMobile();
            });

            chatHistory.appendChild(button);
        });
    }

    function renderActiveChat() {
        const chat = getActiveChat();
        chatArea.innerHTML = "";

        if (!chat || !chat.messages.length) {
            chatArea.appendChild(welcome);
            return;
        }

        chat.messages.forEach(message => {
            addMessageToDOM(message.role, message.content, {
                files: message.files || [],
                imageUrl: message.imageUrl || null,
                persist: false
            });
        });

        scrollToBottom();
    }

    function scrollToBottom() {
        requestAnimationFrame(() => {
            chatArea.scrollTop = chatArea.scrollHeight;
        });
    }

    function addMessageToDOM(role, content, options = {}) {
        const wrapper = document.createElement("div");
        wrapper.className = `message ${role}`;

        const contentWrap = document.createElement("div");
        contentWrap.className = "message-content";

        const name = document.createElement("div");
        name.className = "message-name";
        name.textContent = role === "user" ? "You" : "Zono";

        const bubble = document.createElement("div");
        bubble.className = "bubble";
        bubble.textContent = content || "";

        contentWrap.appendChild(name);
        contentWrap.appendChild(bubble);

        if (options.imageUrl) {
            const card = document.createElement("div");
            card.className = "ai-image-card";

            const img = document.createElement("img");
            img.src = options.imageUrl;
            img.alt = "Image generated by Zono";

            const caption = document.createElement("div");
            caption.textContent = "Generated by Zono";

            card.appendChild(img);
            card.appendChild(caption);
            contentWrap.appendChild(card);
        }

        if (role === "bot") {
            const actions = document.createElement("div");
            actions.className = "message-actions";

            const copy = document.createElement("button");
            copy.className = "action-button";
            copy.type = "button";
            copy.textContent = "Copy";
            copy.addEventListener("click", async () => {
                try {
                    await navigator.clipboard.writeText(content || "");
                    copy.textContent = "Copied";
                    setTimeout(() => copy.textContent = "Copy", 1200);
                } catch {
                    copy.textContent = "Copy failed";
                }
            });

            const speak = document.createElement("button");
            speak.className = "action-button";
            speak.type = "button";
            speak.textContent = "Read aloud";
            speak.addEventListener("click", () => speakText(content || ""));

            actions.appendChild(copy);
            actions.appendChild(speak);
            contentWrap.appendChild(actions);
        }

        wrapper.appendChild(contentWrap);
        chatArea.appendChild(wrapper);
        scrollToBottom();
    }

    function addTyping() {
        const wrapper = document.createElement("div");
        wrapper.className = "message bot";
        wrapper.id = "typingIndicator";

        const contentWrap = document.createElement("div");
        contentWrap.className = "message-content";

        const name = document.createElement("div");
        name.className = "message-name";
        name.textContent = "Zono";

        const typing = document.createElement("div");
        typing.className = "typing";
        typing.innerHTML = "<span></span><span></span><span></span>";

        contentWrap.appendChild(name);
        contentWrap.appendChild(typing);
        wrapper.appendChild(contentWrap);
        chatArea.appendChild(wrapper);
        scrollToBottom();
    }

    function removeTyping() {
        document.getElementById("typingIndicator")?.remove();
    }

    function autoResize() {
        messageInput.style.height = "auto";
        messageInput.style.height = Math.min(messageInput.scrollHeight, 150) + "px";
    }

    function fileToBase64(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();

            reader.onload = () => {
                const result = String(reader.result || "");
                resolve(result.includes(",") ? result.split(",")[1] : result);
            };

            reader.onerror = reject;
            reader.readAsDataURL(file);
        });
    }

    async function prepareFiles(fileList) {
        const selected = Array.from(fileList || []);

        for (const file of selected) {
            if (file.size > 20 * 1024 * 1024) {
                alert(`${file.name} is larger than 20 MB.`);
                continue;
            }

            const data = await fileToBase64(file);

            pendingFiles.push({
                name: file.name,
                type: file.type || "application/octet-stream",
                data
            });
        }

        renderAttachmentPreview();
    }

    function renderAttachmentPreview() {
        attachmentPreview.innerHTML = "";

        pendingFiles.forEach((file, index) => {
            const item = document.createElement("div");
            item.className = "attachment";

            const label = document.createElement("span");
            label.textContent = file.name;

            const remove = document.createElement("button");
            remove.type = "button";
            remove.textContent = "×";
            remove.title = "Remove attachment";
            remove.addEventListener("click", () => {
                pendingFiles.splice(index, 1);
                renderAttachmentPreview();
            });

            item.appendChild(label);
            item.appendChild(remove);
            attachmentPreview.appendChild(item);
        });
    }

    function clearAttachments() {
        pendingFiles = [];
        fileInput.value = "";
        renderAttachmentPreview();
    }

    async function sendMessage() {
        if (isSending) return;

        const message = messageInput.value.trim();
        if (!message && !pendingFiles.length) return;

        const chat = getActiveChat();
        if (!chat) return;

        isSending = true;
        sendButton.disabled = true;

        if (!chat.messages.length && message) {
            chat.title = message.slice(0, 42) + (message.length > 42 ? "…" : "");
        }

        const filesForMessage = pendingFiles.map(file => ({
            name: file.name,
            type: file.type
        }));

        chat.messages.push({
            role: "user",
            content: message || (fileMode === "screenshot" ? "Read this screenshot." : "Please read this file."),
            files: filesForMessage
        });

        renderActiveChat();
        addTyping();

        const filesToSend = pendingFiles.slice();
        clearAttachments();
        messageInput.value = "";
        autoResize();
        saveChats();
        renderHistory();

        try {
            const response = await fetch(`${API_BASE}/api/chat`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    message,
                    files: filesToSend,
                    history: chat.messages.slice(0, -1).map(item => ({
                        role: item.role,
                        content: item.content
                    }))
                })
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "The server could not answer.");
            }

            removeTyping();

            const answer = data.reply || "I couldn't generate an answer.";
            chat.messages.push({
                role: "bot",
                content: answer,
                imageUrl: data.imageUrl || null
            });

            renderActiveChat();
            saveChats();
        } catch (error) {
            removeTyping();

            const errorText = error?.message || "Something went wrong.";
            chat.messages.push({
                role: "bot",
                content: `Sorry, I couldn't complete that request.\n\n${errorText}`
            });

            renderActiveChat();
            saveChats();
        } finally {
            isSending = false;
            sendButton.disabled = false;
            fileMode = "attach";
            messageInput.focus();
        }
    }

    function speakText(text) {
        if (!("speechSynthesis" in window)) {
            alert("Speech playback is not supported by this browser.");
            return;
        }

        window.speechSynthesis.cancel();

        const utterance = new SpeechSynthesisUtterance(text);
        utterance.rate = 1;
        utterance.pitch = 1;
        window.speechSynthesis.speak(utterance);
    }

    function setupVoice() {
        const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;

        if (!SpeechRecognition) {
            voiceButton.addEventListener("click", () => {
                alert("Voice input is not supported by this browser.");
            });
            return;
        }

        recognition = new SpeechRecognition();
        recognition.continuous = false;
        recognition.interimResults = false;
        recognition.lang = "en-US";

        recognition.onstart = () => {
            voiceButton.classList.add("active");
            voiceButton.querySelector("span:last-child").textContent = "Listening";
        };

        recognition.onend = () => {
            voiceButton.classList.remove("active");
            voiceButton.querySelector("span:last-child").textContent = "Voice";
        };

        recognition.onerror = () => {
            voiceButton.classList.remove("active");
            voiceButton.querySelector("span:last-child").textContent = "Voice";
        };

        recognition.onresult = event => {
            const transcript = event.results[0][0].transcript;
            messageInput.value = `${messageInput.value} ${transcript}`.trim();
            autoResize();
        };

        voiceButton.addEventListener("click", () => {
            try {
                recognition.start();
            } catch {}
        });
    }

    function openSidebarMobile() {
        sidebar.classList.add("open");
        backdrop.classList.add("show");
    }

    function closeSidebarMobile() {
        sidebar.classList.remove("open");
        backdrop.classList.remove("show");
    }

    menuButton.addEventListener("click", openSidebarMobile);
    closeButton.addEventListener("click", closeSidebarMobile);
    backdrop.addEventListener("click", closeSidebarMobile);

    newChatButton.addEventListener("click", () => createChat(true));

    attachButton.addEventListener("click", () => {
        fileMode = "attach";
        fileInput.accept = "image/*,.pdf,.doc,.docx,.txt";
        fileInput.click();
    });

    screenshotButton.addEventListener("click", () => {
        fileMode = "screenshot";
        fileInput.accept = "image/*";
        fileInput.click();
    });

    fileInput.addEventListener("change", async event => {
        await prepareFiles(event.target.files);

        if (fileMode === "screenshot" && pendingFiles.length) {
            if (!messageInput.value.trim()) {
                messageInput.value = "Read this screenshot and explain what it shows.";
                autoResize();
            }
        }
    });

    sendButton.addEventListener("click", sendMessage);

    messageInput.addEventListener("input", autoResize);

    messageInput.addEventListener("keydown", event => {
        if (event.key === "Enter" && !event.shiftKey) {
            event.preventDefault();
            sendMessage();
        }
    });

    document.querySelectorAll(".suggestion").forEach(button => {
        button.addEventListener("click", () => {
            messageInput.value = button.dataset.prompt || "";
            autoResize();
            messageInput.focus();
        });
    });

    setupVoice();
    loadChats();
    autoResize();
});
